# Project 1

## Reg_no: DS105

It's important that you fill in your registration number for proper documentation.

In this project you will be creating your own data set from scratch.

Follow the instructions below

## Import numpy and pandas

In [ ]:
# Complete this
import numpy as  np
import pandas as pd

### Create  a dictionary (named student) of 10 students with name, relationship status, age and department columns

In [ ]:
student = {'name':['Chioma','Edet','Sola','Ade','Kola', 'Ola','Adeola','Peter','Muhammed','Chima'],
           'relationship':['single','married','married','single','married','single','complicated','single','complicated','married'],
           'age':[23, 45, 56, 27, 67, 21, 18, 38, 30,49],
           'department':['HR','Technical','Sales','Markerting','Technical','HR','HR','Markerting','Technical','Sales']}

# 10 values in each of the square brackets

### Add cgpa to the dictionary 

In [ ]:
student['cgpa'] = [2.3, 4.5, 1.2, 3.9, 4.8, 4.5, 0.5, 2.6, 2.5, 4.1] # 10 values for the students' cgpa

### Remove relationship status from the dictionary

In [ ]:
student.pop('relationship')  # fill in the key  you want to remove

['single',
 'married',
 'married',
 'single',
 'married',
 'single',
 'complicated',
 'single',
 'complicated',
 'married']

## Convert the dictionary to a dataframe(df)

In [ ]:
df = pd.DataFrame(student)   # complete this
df.head()

name  age  department  cgpa
0  Chioma   23          HR   2.3
1    Edet   45   Technical   4.5
2    Sola   56       Sales   1.2
3     Ade   27  Markerting   3.9
4    Kola   67   Technical   4.8

## Add admission_date (year, month and day)and gender columns to the dataframe


In [ ]:
df['admission_date'] = ['2017-08-04','2020-05-29','2010-06-01','2013-11-04','2022-05-08','2012-12-01','2016-03-04','2014-09-15','2001-08-12','2010-01-24']#complete the code
df['gender'] = ['female','male','male','female','male','male','female','male','male', 'male' ]


# Check the dataframe




In [ ]:
df

name  age  department  cgpa admission_date  gender
0    Chioma   23          HR   2.3     2017-08-04  female
1      Edet   45   Technical   4.5     2020-05-29    male
2      Sola   56       Sales   1.2     2010-06-01    male
3       Ade   27  Markerting   3.9     2013-11-04  female
4      Kola   67   Technical   4.8     2022-05-08    male
5       Ola   21          HR   4.5     2012-12-01    male
6    Adeola   18          HR   0.5     2016-03-04  female
7     Peter   38  Markerting   2.6     2014-09-15    male
8  Muhammed   30   Technical   2.5     2001-08-12    male
9     Chima   49       Sales   4.1     2010-01-24    male

### Create the same dataframe (df2) with all the columns (name,  age, department, admission_date and gender) from a list instead of a dictionary.


In [ ]:
['cgpa'] = [2.3, 4.5, 1.2, 3.9, 4.8, 4.5, 0.5, 2.6, 2.5, 4.1]

In [ ]:
## Check the dataframe
data = [['Chioma',23,'HR',2.3,'2017-08-04','female'],
        ['Edet', 45,'Technical',4.5,'2020-05-29','male'],
        ['Sola', 56,'Sales',1.2,'2010-06-01','male'],
        ['Ade', 27, 'Markerting',3.9,'2013-11-04','female'],
        ['Kola', 67, 'Technical',4.8,'2022-05-08','male'],
        ['Ola', 21, 'HR',4.5,'2012-12-01','male'],
        ['Adeola', 18, 'HR',0.5,'2016-03-04','female'],
        ['Peter', 38, 'Markerting',2.6,'2014-09-15','male'],
        ['Muhammed', 30, 'Technical',2.5,'2001-08-12','male'],
         ['Chima', 49,'Sales',4.1,'2010-01-24','male']]
        
df2 = pd.DataFrame(data= data, columns=['name', 'age', 'department','cgpa', 'admission_date', 'gender'])

## Work on the first dataframe(df) from here on

### Convert df admission_date column to datetime


 first import datetime as dt



Extract the year, month and day as separate columns within the dataset

In [ ]:
df['admission_date'] = pd.to_datetime(df['admission_date'])  # convert the date to datetime object
df['year'] = df['admission_date'].dt.year
# Complete the code and do the same for month and day

In [ ]:
# Check for data types of all columns
# Check for missing values
# Check for percentage of  missing values
df.dtypes # Check for data types of all columns

name                      object
age                        int64
department                object
cgpa                     float64
admission_date    datetime64[ns]
gender                    object
year                       int64
dtype: object

In [ ]:
df.isna().sum().sum() # Check for missing values

0

In [ ]:
df.count().sum().sum()

70

In [ ]:
df.isna().sum().sum()/df.count().sum().sum() * 100 # Check for percentage of  missing values

0.0

In [ ]:
# Check unique values in each of the columns
# Check number of unique values in each of the columns
# Check value counts for each of the columns

In [ ]:
 [df[i].unique() for i in df.columns]# Check unique values in each of the columns

[array(['Chioma', 'Edet', 'Sola', 'Ade', 'Kola', 'Ola', 'Adeola', 'Peter',
        'Muhammed', 'Chima'], dtype=object),
 array([23, 45, 56, 27, 67, 21, 18, 38, 30, 49]),
 array(['HR', 'Technical', 'Sales', 'Markerting'], dtype=object),
 array([2.3, 4.5, 1.2, 3.9, 4.8, 0.5, 2.6, 2.5, 4.1]),
 array(['2017-08-04T00:00:00.000000000', '2020-05-29T00:00:00.000000000',
        '2010-06-01T00:00:00.000000000', '2013-11-04T00:00:00.000000000',
        '2022-05-08T00:00:00.000000000', '2012-12-01T00:00:00.000000000',
        '2016-03-04T00:00:00.000000000', '2014-09-15T00:00:00.000000000',
        '2001-08-12T00:00:00.000000000', '2010-01-24T00:00:00.000000000'],
       dtype='datetime64[ns]'),
 array(['female', 'male'], dtype=object),
 array([2017, 2020, 2010, 2013, 2022, 2012, 2016, 2014, 2001])]

In [ ]:
df.nunique() 
# Check number of unique values in each of the columns

name              10
age               10
department         4
cgpa               9
admission_date    10
gender             2
year               9
dtype: int64

In [ ]:
[df[i].value_counts() for i in df.columns]# Check value counts for each of the columns

[Chioma      1
 Edet        1
 Sola        1
 Ade         1
 Kola        1
 Ola         1
 Adeola      1
 Peter       1
 Muhammed    1
 Chima       1
 Name: name, dtype: int64, 23    1
 45    1
 56    1
 27    1
 67    1
 21    1
 18    1
 38    1
 30    1
 49    1
 Name: age, dtype: int64, HR            3
 Technical     3
 Sales         2
 Markerting    2
 Name: department, dtype: int64, 4.5    2
 2.3    1
 1.2    1
 3.9    1
 4.8    1
 0.5    1
 2.6    1
 2.5    1
 4.1    1
 Name: cgpa, dtype: int64, 2017-08-04    1
 2020-05-29    1
 2010-06-01    1
 2013-11-04    1
 2022-05-08    1
 2012-12-01    1
 2016-03-04    1
 2014-09-15    1
 2001-08-12    1
 2010-01-24    1
 Name: admission_date, dtype: int64, male      7
 female    3
 Name: gender, dtype: int64, 2010    2
 2017    1
 2020    1
 2013    1
 2022    1
 2012    1
 2016    1
 2014    1
 2001    1
 Name: year, dtype: int64]

In [ ]:
# df.info()
# df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   name            10 non-null     object        
 1   age             10 non-null     int64         
 2   department      10 non-null     object        
 3   cgpa            10 non-null     float64       
 4   admission_date  10 non-null     datetime64[ns]
 5   gender          10 non-null     object        
 6   year            10 non-null     int64         
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 688.0+ bytes


In [ ]:
df.describe()

age       cgpa         year
count  10.000000  10.000000    10.000000
mean   37.400000   3.090000  2013.500000
std    16.433029   1.493281     5.930149
min    18.000000   0.500000  2001.000000
25%    24.000000   2.350000  2010.500000
50%    34.000000   3.250000  2013.500000
75%    48.000000   4.400000  2016.750000
max    67.000000   4.800000  2022.000000

In [ ]:
# How many rows and columns do you have? show it with df.shape
df.shape

(10, 7)

In [ ]:
# Subset the dataframe for male gender
df.query('gender== "male"') # complete the code

name  age  department  cgpa admission_date gender  year
1      Edet   45   Technical   4.5     2020-05-29   male  2020
2      Sola   56       Sales   1.2     2010-06-01   male  2010
4      Kola   67   Technical   4.8     2022-05-08   male  2022
5       Ola   21          HR   4.5     2012-12-01   male  2012
7     Peter   38  Markerting   2.6     2014-09-15   male  2014
8  Muhammed   30   Technical   2.5     2001-08-12   male  2001
9     Chima   49       Sales   4.1     2010-01-24   male  2010

In [ ]:
# Find the mean,max, min, sum CGPA
df.cgpa.mean()

3.09

In [ ]:
df.cgpa.max()

4.8

In [ ]:
df.cgpa.min()

0.5

In [ ]:
df.cgpa.sum()

30.9

In [ ]:
df['cgpa'].mean() #.max(), .min(), .sum()

In [ ]:
# Check your df to be sure that you have all the rows and columns
df
# write your data frame to a csv file
df.to_csv('mycsv', index=False)   # complete the code # remeber to set index parameter to False
# Download the csv file

### Submission
Create a folder on your desktop and name it Project 1

Move your notebook and the csv you downloaded to the folder

Create a github account if you haven't

Create a repository for the class and name it Python for Data Science (click on the + sign by the top right corner)

Click upload an existing file 

Drag the Project 1 folder containing your code and the csv file into the Drag here field (Do not click on choose your files)

Click on the repository name to go the repository home page

Click on the address bar to copy the repository link

Submit the link privately to me